; Rotozoom: a rotating, zooming XOR texture in 8.8 fixed point.
; The 256-entry sine table is generated by the x87 at startup; the inner
; loop is pure integer (two adds per pixel). Press ESC to quit.
org 100h
bits 16

BACK_SEG equ 0x7000

section .data
    val_127  dw 127
    val_256  dw 256
    tmp      dw 0
    frame    dw 0
    du       dw 0               ; per-pixel step (8.8)
    dv       dw 0
    u_row    dw 0               ; texture coordinate at start of row
    v_row    dw 0
    sine     times 256 db 0     ; signed sin*127

section .text
start:
    mov ax, 0x13
    int 0x10

    ; ---- sine[i] = round(sin(i*2pi/256) * 127) ----
    finit
    fild word [val_256]
    fldpi
    fld1
    fld1
    faddp                       ; 2
    fmulp                       ; 2pi
    fdivrp                      ; step = 2pi/256
    fldz                        ; angle
    mov di, sine
    mov cx, 256
.gen:
    fld st0
    fsin
    fild word [val_127]
    fmulp
    fistp word [tmp]
    mov al, [tmp]
    mov [di], al
    inc di
    fadd st1
    loop .gen
    finit

    ; ---- palette: three staggered ramps ----
    mov dx, 0x3C8
    xor al, al
    out dx, al
    inc dx
    xor cx, cx
.pal:
    mov al, cl
    shr al, 2
    out dx, al                  ; R = i/4
    mov al, cl
    shl al, 1
    shr al, 2
    out dx, al                  ; G = (2i mod 256)/4
    mov al, cl
    shl al, 2
    shr al, 2
    out dx, al                  ; B = (4i mod 256)/4
    inc cl
    jnz .pal

    mov ax, BACK_SEG
    mov es, ax

main_loop:
    ; zoom = 96 + sine[frame*2]/2  (range ~32..160)
    mov bx, [frame]
    add bx, bx
    and bx, 0xFF
    mov al, [sine+bx]
    cbw
    sar ax, 1
    add ax, 96
    mov bp, ax                  ; BP = zoom

    ; du = cos(frame) * zoom / 64, dv = sin(frame) * zoom / 64
    mov bx, [frame]
    add bx, 64
    and bx, 0xFF
    mov al, [sine+bx]
    cbw
    imul bp
    sar ax, 6
    mov [du], ax
    mov bx, [frame]
    and bx, 0xFF
    mov al, [sine+bx]
    cbw
    imul bp
    sar ax, 6
    mov [dv], ax

    ; centre the rotation on the screen: start = -(160*du) + 100*dv, ...
    mov ax, [du]
    imul ax, ax, -160
    mov bx, [dv]
    imul bx, bx, 100
    add ax, bx
    mov [u_row], ax
    mov ax, [dv]
    imul ax, ax, -160
    mov bx, [du]
    imul bx, bx, -100
    add ax, bx
    mov [v_row], ax

    xor di, di
    mov bx, [du]
    mov dx, [dv]
    mov word [tmp], 200
row_loop:
    mov si, [u_row]
    mov bp, [v_row]
    mov cx, 320
pix_loop:
    mov ax, si
    xor ax, bp
    mov al, ah                  ; texel = (u>>8) xor (v>>8)
    stosb
    add si, bx
    add bp, dx
    loop pix_loop
    ; row step is perpendicular: (u,v) += (-dv, du)
    sub [u_row], dx
    add [v_row], bx
    dec word [tmp]
    jnz row_loop

    inc word [frame]

    ; vsync
    mov dx, 0x3DA
.vs_a:
    in al, dx
    test al, 8
    jnz .vs_a
.vs_b:
    in al, dx
    test al, 8
    jz .vs_b

    ; blit
    push ds
    push es
    mov ax, BACK_SEG
    mov ds, ax
    xor si, si
    mov ax, 0xA000
    mov es, ax
    xor di, di
    mov cx, 32000
    rep movsw
    pop es
    pop ds

    mov ah, 0x01
    int 0x16
    jz main_loop
    mov ah, 0x00
    int 0x16
    cmp al, 27
    jne main_loop

    mov ax, 0x03
    int 0x10
    mov ax, 0x4C00
    int 0x21
