package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println("; Sine lookup table (256 entries, values 0-255)")
	fmt.Println("; Generated by tools/generate_sintable.go")
	fmt.Print("sine_table: db ")

	for i := 0; i < 256; i++ {
		// Convert index to radians (0-255 maps to 0-2π)
		angle := float64(i) * 2.0 * math.Pi / 256.0

		// Calculate sine value and scale to 0-255 range
		// sin() returns -1 to 1, we convert to 0-255
		sinValue := math.Sin(angle)
		scaledValue := int((sinValue + 1.0) * 127.5)

		// Ensure value is in valid range
		if scaledValue < 0 {
			scaledValue = 0
		}
		if scaledValue > 255 {
			scaledValue = 255
		}

		fmt.Print(scaledValue)

		if i < 255 {
			fmt.Print(", ")
		}

		// Line breaks every 16 values for readability
		if (i+1)%16 == 0 && i < 255 {
			fmt.Print("\n           db ")
		}
	}

	fmt.Println()
}
